# Generated by Django 3.2.19 on 2023-06-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_auto_20230612_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(default='Default Value', max_length=100),
        ),
    ]
