# Generated by Django 3.2.19 on 2023-06-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_servicio_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(max_length=100),
        ),
    ]
