# Generated by Django 3.2.19 on 2023-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_alter_servicio_tipo_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='contrato',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivos',
            field=models.ManyToManyField(to='modulos.Archivo'),
        ),
    ]
