# Generated by Django 3.2.19 on 2023-06-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_auto_20230612_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id_servicios',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
