# Generated by Django 3.2.19 on 2023-06-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0007_auto_20230612_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='servicios',
        ),
        migrations.AddField(
            model_name='contrato',
            name='servicios',
            field=models.ManyToManyField(to='modulos.Servicio'),
        ),
    ]
