# Generated by Django 3.2.19 on 2023-06-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_auto_20230613_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='modulos.Servicio'),
        ),
    ]
