# Generated by Django 3.2.19 on 2023-06-13 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0009_alter_contrato_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='servicios',
        ),
        migrations.AddField(
            model_name='servicio',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.contrato'),
        ),
    ]
