# Generated by Django 3.2.19 on 2023-06-13 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0011_auto_20230613_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='servcio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.tiposervicio'),
        ),
    ]
