# Generated by Django 3.2.19 on 2023-06-15 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0012_auto_20230613_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='id_servicios',
            new_name='id_servicio',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='servcio',
            new_name='tipo_servicio',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivo',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='ejecutivo',
            name='id_ejecutivo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
