# Generated by Django 3.2.19 on 2023-07-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0013_auto_20230614_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colegio', models.CharField(max_length=100)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('cant_alumnos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cant_alumnos',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='colegio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='ejecutivo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nombre_curso',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nombre_rep_legal',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='rut_rep_legal',
        ),
        migrations.AddField(
            model_name='contrato',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=23000, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulos.institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='representante_legal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulos.representantelegal'),
            preserve_default=False,
        ),
    ]
