# Generated by Django 3.2.19 on 2023-07-12 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0015_auto_20230712_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ejecutivo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='modulos.ejecutivo'),
            preserve_default=False,
        ),
    ]
